### PR TITLE
Change download regex

### PR DESCRIPTION
**Pull request by tuxudo**

### CODE REVIEW

**Comment by jazzace** [comment]
I'm going to reject this PR primarily because it removes capturing the version number via the regular expression (and would thus break a dependency for the pkg recipe). But I'm curious what URL you are seeing for the download. I changed the recipe yesterday to reflect the new URL I am seeing plus the previous URL. I'm guessing your mirror is not in the NW United States. Your PR would not capture the URL I am seeing (https://ftp.osuosl.org/pub/musescore/releases/MuseScore-3.0.2/MuseScore-3.0.2.dmg).

**Comment by jazzace** [comment]
Might the link be 
https://github.com/musescore/MuseScore/releases/download/v3.0.2/MuseScore-3.0.2.dmg ?

**Comment by jazzace** [comment]
I've update the recipe with a fix that will see both the GitHub URL (which I am seeing today) and the osuosl.org URL (which I was seeing yesterday). It should also capture the URL we were seeing before that. Thanks for the quick catch on this and bringing it to my attention with a PR. I will now close this.

**Comment by tuxudo** [comment]
Welcome! I tried to get it to capture the regex for the version number, but wasn't able to get it to work.

**Pull request closed without merging**
